### ISSUE TITLE
demo tick data bonkers on 26th 27th may 2022

### ISSUE THREAD

**Issue by clearoak** [fxcm/RestAPI#200]
The demo tick data started intermitently pushing times from jan 1970 from 4pm BST yesterday!   And before that, at some time, it started pushing datetimes of 1000 times more precision.  Anyone aware?  At this point, *all* the dates are 1970-01-20 03:20:32 and change.

**Comment by FXCMAPI** [comment]
Hi,

There was an issue on our server side yesterday, which should have been resolved now.

**Comment by clearoak** [comment]
Hi there, 

By the end of Friday, there was still an issue.  If you just print stuff, it's like this:

UK100 | 1970-01-20 03:21:12.648000 | 7583.11000, 7585.61000
or
SPX500 | 1970-01-20 03:21:13.062000 | 4127.15000, 4127.65000

The Unix time has reduced from microseconds to milliseconds after 1st Jan 1970 but as you can see, all is not well.

**Comment by DanielMRBL** [comment]
I solved this issue by making these changes in my fxcmpy.py localy:

Within the fxcm-method(s):
            # date = pd.to_datetime(int(data['Updated']), unit='ms') # old-version
            date = self.dmb_to_datetime(data['Updated']) # new-version

The additional method of mine:

    def dmb_to_datetime(self, pv_data):
        date = None
        try: 
            for i in range(1,len(str(pv_data))):
               date = pd.to_datetime(int(str(pv_data)[0:i]), unit = 'ms')
        except:
            pass
        return date

It helps me to keep my project alive. :)

Kind regards 
Daniel

**Comment by FXCMAPI** [comment]
@clearoak this is due to changing unit to 'us' as I advised you earlier. Now as the issue is solved on our server side please set it back to 'ms' and it will start showing the current date.

Best Regards,
Valentin
